name = input("Please write your nickname: ")
print(f"Hello, {name}")
nig = input(f"{name}, may I ask you a question? ")
date = input("What is the date today? ")
print(f"Oh, today is {date}?")
syn = input("")
print("So, today is our 5th anniversary? ")
sagot = "No"
while sagot == "No":
    sagot = input("Yes/No: ")
    if sagot == "No":
        print("Mag-yes ka na, pakipot ka pa  ")
print(f"Mahal na mahal kita {name}")
nice = input("Put your Favorite Bible Verse: ")
print()
print()
print()
print()
print("Happy anniversary bebe ko, thank you sa araw-araw na pananatili at pagpu-push harder palagi sa akin,") 
print()
print("tho may mga pagkakataon na hindi tayo nagkakaunawaan but still we chose to stay no matter what. ")
print()
print("Sobrang thankful ako kasi mayroon akong IKAW, kumbaga parang kape, ALL IN ONE!. ")
print()
print(f"Mahal na mahal kita {name} ko! tutulungan kita hanggang sa kung anong makakaya ko, emotional man, ")
print()
print("psychological, financial, physical, and spiritual. ")
print()
print("I just want you to know na how big our argument is hinding-hindi kita iiwan.  ")
print()
print("Palagi lang akong nasa likod mo naka support sayo, palagi natin kakayanin kasi kailangan. ")
print()
print("Marami pa tayong kailangan i-explore so i-enjoy natin lahat ng bagay even tho")
print()
print("hindi masyadong mahalaga kasi at the end of the day, all we need is peace and joy. ")
print()
print("Tutulungan kitang maka graduate diyan sa dream school mo bebe, tho nakikita mong tamad me now ")
print()
print("pero hayaan mo kapag nakapag tapos na ako aalisin ko na lahat ng bad habits ko ")
print()
print("para makabawi ako sa family ko and also sayo kasi palagi mo ako sinasalo kapag kulang ako. ")
print()
print(f"Sobrang saya ko na nakilala kita {name} hindi ko na makita sarili ko sa iba simula nung dumating ka. ")
print()
print("Kapag dumating na yung time na nakapag tapos na ako, ako naman mangs-spoil sayo.")
print()
print("Ang wish ko lang ay magkaron pa tayo nang mas mahaba na pagsasama, ")
print()
print("mas piliing controlin ang galit sa isa't isa, ibigay palagi ang best, ")
print()
print("wag kalimutan huminga nang matiwasay, alagaan mo health mo kasi mag ttravel pa tayo kung saan-saan. ")
print()
print("Sana ay maabot natin ang mga pangarap na minsan nating isinakripsiyo. Huwag kang mag-alala, ")
print()
print("magiging dentist ka. Always live your best life kasi walang permanente sa mundo, ")
print()
print("hindi natin alam kung kailan tayo mawawala kaya kapag meron kang doubt, ")
print()
print("run into the Lord and He will erase it. ")
print()
print("Palagi kang mag-ask kay Lord ng guidance. ")
print()
print("I will surely miss you bebe kapag nasa malayo ka na pero pupuntahan kita, promise ko sayo yan. ")
print()
print("Gagala tayo kahit saan mo gusto kapag magkasama tayo. ")
print()
print("Tiis lang tayo bebe once na makamit na natin to, hindi na tayo maghihiwalay promise ko sayo yan. ")
print()
print(f"I love you {name} ko, mahal kita higit pa sa nalalaman mo. Sana nagustuhan mo tong gawa ko :) ")
print()
print("You may not understand what I am doing right now, but one day it will all make sense.")
print()
print("John 13:7")
print()
print()
yester = "No"
while yester == "No":
    print()
    yester = input("Nagustuhan mo ba? ")
    if yester == "No":
        print("Mag ye-yes na yan, yieeee ")
print()
print("I love you, nasa cabinet gift mo hehehehe HOPE U LIKE IT :> ")